import DesktopNav from "./Components/DesktopNav";
import MobileNav from "./Components/MobileNav";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-full relative overflow-hidden flex flex-col  lg:flex-row px-4 py-10 pt-4 md:px-10 lg:px-0  lg:py-0 lg:h-screen bg-[#FDFDFD] max-w-screen-2xl mx-auto">
          <MobileNav />
          <DesktopNav />
          <main className="overflow-auto lg:px-8 lg:py-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
